services:
  - type: web
    name: django-chatbot
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn chatbot_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_project.settings
      - key: PYTHON_VERSION
        value: 3.11
